UnitedAccessoriesLimited/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UAL.BLL.Data;
using UAL.BLL.Models;

namespace UnitedAccessoriesLimited.Controllers
{
    public class SalesController : Controller
    {
        //
        // GET: /Sales/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult Create(Sale s)
        {
            string[] size = Request.Form.GetValues("size[]");
            string[] qty = Request.Form.GetValues("qty[]");
            s.Status = "Pending";
            s.ProductionHours = Convert.ToInt32(Math.Ceiling(Convert.ToDouble(s.OrderQty) * Convert.ToDouble(s.Pick) / Convert.ToDouble(s.Cutter) / 600 / 60));
            s.WOIssueDate = DateTime.ParseExact(Request.Form["issuedate"], "dd-MMMM-yyyy", CultureInfo.InvariantCulture);
            OrderRepository or = new OrderRepository();
            s.WO = or.generateWONumber(s.Label);
            if (or.createSales(s, size, qty) == 1)
            {
                Session["SalesCreated"] = "Sales Item Created Successfully";
            }
            return View();
        }
        public ActionResult SalesList()
        {
            OrderRepository o = new OrderRepository();
            string s = Request.Form["issuedate"];
            string month = "";
            string[] date = s.Split('-');
            switch (date[0])
            {
                case "January": { month = "01"; break; }
                case "February": { month = "02"; break; }
                case "March": { month = "03"; break; }
                case "April": { month = "04"; break; }
                case "May": { month = "05"; break; }
                case "June": { month = "06"; break; }
                case "July": { month = "07"; break; }
                case "August": { month = "08"; break; }
                case "September": { month = "09"; break; }
                case "October": { month = "10"; break; }
                case "November": { month = "11"; break; }
                case "December": { month = "12"; break; }
            }

            string year = date[1];
            Session["Month"] = date[0];
            Session["Year"] = year;
            Session["Label"] = Request.Form["label"];
            List<Sale> los = o.getSalesList(Request.Form["label"], month, year);
            return View(los);
        }

    }
}

UnitedAccessoriesLimited/Views/Sales/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(function () {
        $("#issuedate").datepicker({
            dateFormat: 'MM-yy', changeMonth: true,
            changeYear: true, showButtonPanel: true,
            onClose: function (dateText, inst) {
                $(this).datepicker('setDate', new Date(inst.selectedYear, inst.selectedMonth, 1));
            }
        });
    });
</script>
<style>
    .ui-datepicker-calendar {
        display: none;
    }
</style>
<div id="main1" style="margin-left:195px">
    @Html.ActionLink("CREATE UAL WORK ORDER", "Create", new { }, new { @class = "btn btn-default" })
    @using (Html.BeginForm("SalesList", "Sales", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <select id="label" name="label" required class="ddl">
            <option>WOVEN</option>
            <option>NEEDLE</option>
            <option>PRINTED</option>
            <option>OFFSET</option>
            <option>RIBBON</option>
        </select>
        <input type="text" id="issuedate" name="issuedate" required/>
    <input type="submit" class="btn btn-default" value="Get Sales Report" />

    }
</div>

UnitedAccessoriesLimited/Views/Sales/SalesList.cshtml
@model IEnumerable<UAL.BLL.Models.Sale>

@{
    ViewBag.Title = "SalesList";
}
<div id="main1" style="margin-left:195px">
    <h2 style="text-align:center">TOTAL SALES STATUS</h2>
    <h2 style="text-align:center">@Session["Month"], @Session["Year"] @Session["label"]</h2>
    <h2 style="text-align:center">UNION ACCESSORIES LIMITED</h2>
    <p>
        @Html.ActionLink("Create New", "Create", new { }, new { @class = "btn btn-default" })
    </p>
    <table class="table table-striped table-bordered" cellspacing="0" width="100%">

        <thead>
            <tr>
                <th colspan="13"></th>
                <th>
                    @Model.Sum(d => Convert.ToDecimal(d.OrderQty)).ToString()
                </th>
                <th>
                    @Math.Round(Model.Sum(d => Convert.ToDecimal(d.OrderQty) / 12), 2)
                </th>
                <th colspan="4"></th>
                <th>
                    @Model.Sum(d => Convert.ToDecimal(d.TotalAmount))
                </th>
                <th></th>
                <th>
                    @Model.Sum(d => Convert.ToDecimal(d.FinishingTotalAmount))
                </th>
                <th>
                    @Model.Sum(d => Convert.ToDecimal(d.GTotalAmount))
                </th>
                <th>
                    @Model.Sum(d => Convert.ToDecimal(d.AmountReceived))
                </th>
                <th>@Model.Sum(d => Convert.ToDecimal(d.OrderwiseAmountDue))</th>
                <th></th>
                <th></th>
            </tr>
            <tr>
                <th>
                    W/O Issue  DATE
                </th>
                <th>
                    W/O #
                </th>
                <th>
                    CUSTOMER NAME
                </th>
                <th>
                    BUYER
                </th>
                <th>
                    PO #
                </th>
                <th>
                    CUSTOMER ORDER REF. #
                </th>
                <th>
                    SL #
                </th>
                <th>
                    UAL  FILE NAME
                </th>
                <th>
                    LABEL TYPE
                </th>
                <th>
                    LABEL NAME
                </th>
                <th>
                    Finishing
                </th>
                <th>
                    VERSION
                </th>
                <th>
                    Buyer's REF#
                </th>
                <th>
                    ORDER QTY (Pcs)
                </th>
                <th>
                    ORDER QTY (DZN)
                </th>
                <th>
                    PICK
                </th>
                <th>
                    CUTTER
                </th>
                <th>
                    BEAM
                </th>
                <th>
                    RATE per
                    DZN.
                    ($)
                </th>
                <th>
                    TOTAL  AMOUNT
                    ($)
                </th>
                <th>
                    Finishing
                    RATE per
                    DZN.($)
                </th>
                <th>
                    Finishing
                    TOTAL
                    AMOUNT
                    ($)
                </th>
                <th>
                    G/ TOTAL
                    Amount
                    ($)
                </th>
                <th>
                    AMOUNT
                    RCVD. $
                </th>
                <th>
                    Order wise
                    AMOUNT DUE
                    ($)
                </th>
                <th>
                    PROD. HRS.
                </th>
                <th>
                    PRIORITY
                </th>
                <th>
                    Department
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.WOIssueDate.ToString("dd-MMMM-yy")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.WO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Buyer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerOrderRef)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SL)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UALFileName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LabelType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LabelName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Finishing)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Version)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BuyersRef)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderQty)
                    </td>
                    <td>
                        @{decimal x = Convert.ToDecimal(item.OrderQty) / 12;}
                        @Math.Round(x, 2)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pick)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cutter)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Beam)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RatePerDzn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FinishingRate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FinishingTotalAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GTotalAmount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AmountReceived)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderwiseAmountDue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductionHours)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Priority)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Label)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>