UnitedAccessoriesLimited/Controllers/ArtworkController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UAL.BLL.DataModel;
using UAL.BLL.Data;
using UAL.BLL.Models;
namespace UnitedAccessoriesLimited.Controllers
{
    public class ArtworkController : BaseController
    {
        //
        // GET: /Artwork/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Edit(string refN)
        {
            DataLayer dl = new DataLayer();
            ArtWorkUpload au = dl.findArtwork(refN);
            return View(au);
        }
        [HttpPost]
        public ActionResult Edit(ArtWorkUpload au){
            DataLayer dl = new DataLayer();
            if(dl.EditArtwork(au)==1){

            }
            return View();
        }
        //
        // GET: /Artwork/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Artwork/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Artwork/Create
        
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Artwork/Edit/5

        public ActionResult DropFiles()
        {
            if (goToLogin() == false)
                return RedirectToAction("Login", "Home");
            return View();

        }
        public ActionResult UploadImageForSample(string label, string refN, string combo, string buyer, DateTime doS)
        {
            string newFileName = label + "_" + refN + "_" + combo + "_" + buyer + "_" + doS.ToString("dd-MM-yyyy");
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var subPath = Server.MapPath("~/NewFolder2/");
                    string ext = Path.GetExtension(fileName);
                    var path = Path.Combine(subPath, newFileName + ext);
                    if (!Directory.Exists(subPath))
                    {
                        Directory.CreateDirectory(subPath);
                    }
                    if (Directory.Exists(path))
                        Directory.Delete(path);

                    file.SaveAs(path);
                    @TempData["ImageSubmitted"] = "Art Work with reference - " + refN + " was Submitted Successfully";
                }
                else
                {
                    @TempData["ImageSubmitted"] = "Failed to upload Art Work for reference - " + refN;
                }
            }
            return RedirectToAction("SampleDetails", new { refN = refN });
        }
        [HttpPost]
        public ActionResult Upload(Sample s)
        {
            DataLayer dl = new DataLayer();

            string referenceGen = "";
            if (s.Reference == null)
            {
                s.Reference = dl.ReferenceGenerator(s);
            }
            referenceGen = s.Reference;
            DateTime x = DateTime.ParseExact(Request.Form["date"], "dd-MMMM-yyyy", CultureInfo.InvariantCulture);
            string doSS = Convert.ToDateTime(x, CultureInfo.GetCultureInfo("en-US")).ToString("dd-MM-yyyy");
            string labelforFile = shortLabel(s.Label);
            string newFileName = labelforFile + "_" + referenceGen + "_" + s.Combo + "_" + s.Buyer + "_" + doSS;
            s.comments = Request.Form["comments"];

            if (dl.submitSample(s, x, Session["UserName"].ToString()) == 1)
            {
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var subPath = Server.MapPath("~/NewFolder2/");
                        string ext = Path.GetExtension(fileName);
                        var path = Path.Combine(subPath, newFileName + ext);
                        if (!Directory.Exists(subPath))
                        {
                            Directory.CreateDirectory(subPath);
                        }
                        file.SaveAs(path);
                        @TempData["Submitted"] = "Art Work with reference - " + s.Reference + " was Submitted Successfully";
                    }
                    else
                    {
                        @TempData["Submitted"] = "Failed to upload Art Work for reference - " + s.Reference;
                    }
                }
            }
            else { @TempData["Submitted"] = "Art Work with reference - " + s.Reference + " exists."; }
            return RedirectToAction("DropFiles");
        }
        public ActionResult PendingSamples()
        {
            if (goToLogin() == false)
                return RedirectToAction("Login", "Home");

            DataLayer dl = new DataLayer();
            List<Sample> ls = new List<Sample>();
            ls = dl.getSamples();
            return View(ls);
        }
        public new ActionResult Profile()
        {
            if (goToLogin() == false)
                return RedirectToAction("Login", "Home");
            DataLayer dl = new DataLayer();
            List<ArtWorkUpload> ls = new List<ArtWorkUpload>();
            ls = dl.getSamples(Session["UserName"].ToString());
            return View(ls);
        }
        public ActionResult sendToFactory(string refN)
        {
            DataLayer dl = new DataLayer();
            if (dl.updateSample(refN, "Pending In Factory") == 1)
            {
                @TempData["sendToFactory"] = "Label " + refN + " is sent to UAL factory..";
            }
            return RedirectToAction("PendingSamples");
        }
        public FileStreamResult viewSample(string label, string refN, string combo, string Buyer, DateTime doS)
        {
            if (goToLogin() == false)
                RedirectToAction("Login", "Home");
            label = shortLabel(label);
            string doSS = Convert.ToDateTime(doS, CultureInfo.GetCultureInfo("en-US")).ToString("dd-MM-yyyy");
            string fileName = label + "_" + refN + "_" + combo + "_" + Buyer + "_" + doSS;
            if (Session["UserName"] != null)
            {
                try
                {
                    @TempData["fileError"] = "";
                    FileStream fs = new FileStream(Server.MapPath("~/NewFolder2/" + fileName + ".pdf"), FileMode.Open, FileAccess.Read);
                    return File(fs, "application/pdf");

                }
                catch (Exception ex)
                {
                    @TempData["fileError"] = ex.ToString();
                }
            }
            return null;

        }
        public string shortLabel(string label)
        {
            string labelforFile = "";
            switch (label)
            {
                case "Woven Department": { labelforFile = "WL"; break; }
                case "Printed Department": { labelforFile = "PL"; break; }
                case "Offset Department": { labelforFile = "OP"; break; }

            }
            return labelforFile;
        }
        public bool goToLogin()
        {
            if (Session["UserName"] == null)
                return false;
            else return true;
        }
        public ActionResult PendingInFactory()
        {
            if (goToLogin() == false)
                return RedirectToAction("Login", "Home");

            DataLayer dl = new DataLayer();
            List<ArtWorkUpload> ls = new List<ArtWorkUpload>();
            ls = dl.getSamplesInFactory("Pending In Factory");
            return View(ls);
        }
        public ActionResult deliveredToUAL(string refN)
        {
            DataLayer dl = new DataLayer();
            if (dl.updateSample(refN, "DeliveredToUAL") == 1)
            {
                @TempData["deliveredToUAL"] = "Sample is ready and sent for Reference:" + refN + "..";
            }
            return RedirectToAction("PendingInFactory");
        }
        public ActionResult ReadyForBuyer(string refN)
        {
            DataLayer dl = new DataLayer();
            List<ArtWorkUpload> ls = new List<ArtWorkUpload>();
            if (refN == null) ls = dl.getSamplesInFactory("DeliveredToUAL");
            else
            {

                List<ArtWorkUpload> tsu = dl.searchArtWorks(refN, "DeliveredToUAL");

                return View(tsu);
            }
            return View(ls);
        }
        public ActionResult submitToBuyer(string refN)
        {
            string price = Request.Form["price"];
            string finishing = Request.Form["finishing"];
            string note = Request.Form["note"];
            DateTime SentForApprovalDate = DateTime.ParseExact(Request.Form["sentForApprovalDate"], "dd-MMM-yy", CultureInfo.InvariantCulture); ;
            DataLayer dl = new DataLayer();
            if (dl.SubmitToBuyer(refN, price, finishing, note, SentForApprovalDate) == 1)
            {
                TempData["Status"] = "Submitted to Buyer...";
            }



            return RedirectToAction("ReadyForBuyer");
        }
        public ActionResult Search()
        {
            string search = Request.Form["search"];
            return RedirectToAction("ReadyForBuyer", new { refN = search });
        }
        public ActionResult Approval()
        {
            DataLayer dl = new DataLayer();
            List<ArtWorkUpload> su = dl.getSamplesInFactory("SendForApproval");

UnitedAccessoriesLimited/Views/Artwork/Approval.cshtml
@model IEnumerable<UAL.BLL.Models.ArtWorkUpload>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(function () {
        $(".approvaldate").datepicker({ dateFormat: 'dd-M-y' });
    });
</script>
@{
    ViewBag.Title = "Approval";
}
<div style="margin-left:195px;" id="main1">
    @Session["ApprovedByBuyer"]
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>
                    BUYER
                </th>
                <th>
                    BRAND
                </th>
                <th>
                    DIVISION
                </th>
                <th>
                    DEPARTMENT
                </th>
                <th>
                    DESCRIPTION
                </th>
                <th>
                    REFERENCE
                </th>


                <th>
                    COMBO
                </th>
                <th>
                    VERSION
                </th>

                <th>APPROVAL DATE</th>
                <th>APPROVED BY</th>
                <th>Action</th>
                <th>COMMENTS</th>
                <th>Action</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.buyer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.brand)
                    </td>
                    <td></td>
                    <td>
                        @Html.DisplayFor(modelItem => item.label)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.itemDescription)
                    </td>
                    <td>
                        @Html.ActionLink(item.refNumber, "sampleDetails", "Artwork", new { refN = item.refNumber }, new {@class = "btn btn-default", target = "_blank" })
                    </td>


                    <td>
                        @Html.DisplayFor(modelItem => item.combo)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.version)
                    </td>

                    @using (Html.BeginForm("ApprovedByBuyer", "Artwork", new { refN = item.refNumber }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <td>
                            <input class="approvaldate" name="approvaldate" style="max-width:100px" required type="text">
                        </td>
                        <td>
                            <input id="buyer" name="buyer" type="text" style="max-width:100px" required />
                        </td>
                        <td>
                            <input type="submit" class="btn btn-default" name="submit" id="submit" value="Approved" />
                        </td>
                    }
                    @using (Html.BeginForm("RejectedByBuyer", "Artwork", new { refN = item.refNumber }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <td>
                            <textarea id="comments" name="comments" style="max-width:100px" required></textarea>
                        </td>
                        <td>
                            <input type="submit" class="btn btn-default" name="submit" id="submit" value="Rejected" />
                        </td>
                    }
                </tr>
            }
        </tbody>

    </table>
</div>

UnitedAccessoriesLimited/Views/Artwork/ApprovedSamples.cshtml
@model IEnumerable<UAL.BLL.Models.ArtWorkUpload>

@{
    ViewBag.Title = "ApprovedSamples";
}
<div style="margin-left:195px" id="main1">
    <table class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>
                    REFERENCE
                </th>
                <th>
                    DEPARTMENT
                </th>
                <th>
                    VERSION
                </th>
                <th>
                    COMBO
                </th>
                <th>
                    ITEM DESCRIPTION
                </th>
                <th>
                    BRAND
                </th>
                <th>
                    Receiving Date
                </th>
                <th>
                    Approval Date
                </th>
                <th>
                    BUYER
                </th>
                <th>
                    COMMENTS
                </th>
                
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.refNumber, "sampleDetails", new { refN = item.refNumber }, new {@class = "btn btn-default", target = "_blank" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.label)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.version)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.combo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.itemDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.brand)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.dateOfSubmission)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOfApproval)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.buyer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.comments)
                    </td>

                </tr>
            }
        </tbody>

    </table>
</div>

UnitedAccessoriesLimited/Views/Artwork/DropFiles.cshtml
@model UAL.BLL.DataModel.Sample

@{
    ViewBag.Title = "DropFiles";
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(function () {
        $("#date").datepicker({ dateFormat: 'dd-MM-yy' });
        $("#deliveryDate").datepicker({ dateFormat: 'dd-MM-yy' });
    });
</script>
<div style="margin-left:195px">
    
</div>
@using (Html.BeginForm("Upload", "Artwork", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    
    <fieldset id="main1" style="margin-left:195px; margin-top:100px;">
        @TempData["Submitted"]
        <legend>Upload Art work</legend>
        <table>
            <tr>
                <td class="editor-label">
                    @Html.LabelFor(model => model.Reference)
                </td>
                <td class="editor-field">
                    @Html.EditorFor(model => model.Reference)
                    @Html.ValidationMessageFor(model => model.Reference)

                </td>
            </tr>
            <tr>
                <td class="editor-label">
                    @Html.LabelFor(model => model.Description)
                </td>
                <td class="editor-field">
                    @Html.EditorFor(model => model.Description, new { required = "required" })
                    @Html.ValidationMessageFor(model => model.Description)
                </td>
            </tr>
            <tr>
                <td class="editor-label">
                    <label>DEPARTMENT</label>
                </td>
                <td class="editor-field">
                    @Html.DropDownListFor(model => model.Label, new List<SelectListItem>
                 { new SelectListItem{Text="Woven Department", Value="Woven Department"},
                 new SelectListItem{Text="Printed Department", Value="Printed Department"},
                 new SelectListItem{Text="Offset Department",Value="Offset Department"}}, "Select Department...", new { @class = "ddl" })
                    @Html.ValidationMessageFor(model => model.Label)
                </td>
            </tr>
            <tr>
                <td class="editor-label">
                    @Html.LabelFor(model => model.Combo)
                </td>
                <td class="editor-field">
                    @Html.DropDownListFor(model => model.Combo, new List<SelectListItem>
       {
           new SelectListItem{Text="A", Value="A"},
           new SelectListItem{Text="B", Value="B"},
           new SelectListItem{Text="C", Value="C"},
           new SelectListItem{Text="D", Value="D"},
           new SelectListItem{Text="E", Value="E"},
           new SelectListItem{Text="F", Value="F"},
           new SelectListItem{Text="G", Value="G"},
           new SelectListItem{Text="H", Value="H"},
           new SelectListItem{Text="I", Value="I"},
           new SelectListItem{Text="J", Value="J"},
           new SelectListItem{Text="K", Value="K"},
           new SelectListItem{Text="L", Value="L"},
           new SelectListItem{Text="1", Value="1"},
           new SelectListItem{Text="2", Value="2"},
           new SelectListItem{Text="3", Value="3"},
           new SelectListItem{Text="4", Value="4"},
           new SelectListItem{Text="5", Value="5"},

       }, "Select Combo...", new { @class = "ddl" })


                    @Html.ValidationMessageFor(model => model.Combo)
                </td>
            </tr>
            <tr>
                <td class="editor-label">
                    @Html.LabelFor(model => model.version)
                </td>
                <td class="editor-field">
                    @Html.DropDownListFor(model => model.version, new List<SelectListItem>
       {
           new SelectListItem{Text="US Version", Value="US Version"},
           new SelectListItem{Text="Canada Version", Value="Canada Version"},

       }, "Select Version...", new { @class = "ddl" })
                    @Html.ValidationMessageFor(model => model.version)
                </td>
            </tr>
            <tr>
                <td class="editor-label">
                    @Html.LabelFor(model => model.Brand)
                </td>
                <td class="editor-field">
                    @Html.EditorFor(model => model.Brand)
                    @Html.ValidationMessageFor(model => model.Brand)
                </td>
            </tr>
            <tr>
                <td class="editor-label">
                    @Html.LabelFor(model => model.Buyer)
                </td>
                <td class="editor-field">
                    @Html.EditorFor(model => model.Buyer)
                    @Html.ValidationMessageFor(model => model.Buyer)
                </td>
            </tr>
            <tr>
                <td class="editor-label">
                    @Html.LabelFor(model => model.comments)
                </td>
                <td class="editor-label">
                    <textarea rows="4" cols="30" id="comments" name="comments"></textarea>
                </td>
            </tr>
            <tr>
                <td class="editor-label">
                    <label>Artwork Receiving Date</label>
                </td>
                <td class="editor-label">
                    <input type="text" id="date" name="date" required />

                </td>

            </tr>
            <tr>
                <td class="editor-label">
                    <label>Artwork Received From</label>
                </td>
                <td class="editor-label">
                    @Html.EditorFor(model => model.ReceivedFrom)
                    @Html.ValidationMessageFor(model => model.ReceivedFrom)
                </td>

            </tr>
            <tr>
                <td>
                    <input type="file" name="file" onchange="getFileName()" required />
                </td>
                <td id="fileName">
                    @TempData["FileName"]
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="Submit" id="Submit" class="mySubmit" value="Submit Sample" onclick="disableSubmit()" />
                </td>
            </tr>
        </table>
    </fieldset>
}

<script>
    function getFileName() {
        var fileN = $('input[type=file]').val();
        fileN = fileN.slice(12);
        document.getElementById("fileName").innerHTML = fileN;
    }
    function disableSubmit() {
        document.getElementById("Submit").hidden = true;
    }
</script>

UnitedAccessoriesLimited/Views/Artwork/Edit.cshtml
@model UAL.BLL.Models.ArtWorkUpload

@{
    ViewBag.Title = "Edit";
}
<div id="main1" style="margin-left:195px">
    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>ArtWorkUpload</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.refNumber)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.refNumber)
                @Html.ValidationMessageFor(model => model.refNumber)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.itemDescription)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.itemDescription)
                @Html.ValidationMessageFor(model => model.itemDescription)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Price)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
            <p>
                <input type="submit" value="Save" />
            </p>
        </fieldset>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>


</div>

UnitedAccessoriesLimited/Views/Artwork/PendingInFactory.cshtml
@model IEnumerable<UAL.BLL.Models.ArtWorkUpload>

@{
    ViewBag.Title = "PendingInFactory";
}
<div id="main1" style="margin-left: 195px;">
    <h2>Pending In Factory</h2>
    @TempData["deliveredToUAL"]
    <table class="table table-hover table-responsive">
        <thead>
            <tr>
                <th>
                    Reference
                </th>
                <th>
                    Label
                </th>
                <th>
                    Version
                </th>
                <th>
                    Combo
                </th>
                <th>
                    Description
                </th>
                <th>
                    Brand
                </th>
                <th>
                    Submission Date
                </th>
                <th>
                    Buyer
                </th>
                <th>
                    Comments
                </th>
                <th>
                    Creator
                </th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.ActionLink(item.refNumber, "sampleDetails", new { refN = item.refNumber }, new { target = "_blank", @class="btn btn-default" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.label)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.version)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.combo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.itemDescription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.brand)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.dateOfSubmission)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.buyer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.comments)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.createdBy)
                    </td>
                    <td>
                        @Html.ActionLink("Deliver to UAL", "deliveredToUAL", new { refN = item.refNumber }, new { @class = "btn btn-default" })
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

UnitedAccessoriesLimited/Views/Artwork/ReadyForBuyer.cshtml
@model IEnumerable<UAL.BLL.Models.ArtWorkUpload>

@{
    ViewBag.Title = "ReadyForBuyer";
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
@*<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>*@
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $(function () {
        $(".sentForApprovalDate").datepicker({ dateFormat: 'dd-M-y' });
    });
</script>


<div style="margin-left: 195px;" id="main1">

    @Session["PriceUpdate"]

    <table class="table table-hover table-responsive">
        <thead>
            <tr>
                <th>
                    Reference
                </th>
                <th>
                    Department
                </th>
                <th>
                    Version
                </th>
                <th>
                    Combo
                </th>
                <th>
                    Description
                </th>

                <th>
                    Receiving Date
                </th>


                @if (Session["UserType"] != null && Session["UserType"].ToString() == "Admin")
                {
                    <th>Price</th>
                    <th>Finishing</th>
                    <th>Note</th>
                    <th>Sent for Approval Date</th>
                    <th>Action</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.refNumber, "sampleDetails", new { refN = item.refNumber }, new {@class = "btn btn-default", target = "_blank" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.label)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.version)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.combo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.itemDescription)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.dateOfSubmission)
                    </td>


                    @if (Session["UserType"].ToString() == "Admin")
                    {
                        using (Html.BeginForm("submitToBuyer", "Artwork", new { refN = item.refNumber }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <td>
                                <input id="price" name="price" type="number" min="0" step="0.01" style="max-width:70px" required />
                            </td>
                            <td>
                                <textarea id="finishing" name="finishing" style="max-width:100px" required></textarea>
                            </td>
                            <td>
                                <textarea id="note" name="note" style="max-width:150px" required></textarea>
                            </td>
                            <td>
                                <input class="sentForApprovalDate"  name="sentForApprovalDate" style="max-width:100px" required type="text">
                            </td>
                            <td>
                                <input id="submit" class="btn btn-default" name="submit" type="submit" value="Submit To Buyer" style="" />
                            </td>
                        }
                    }
                </tr>
            }
        </tbody>

    </table>
</div>