UnitedAccessoriesLimited/Controllers/FollowUpController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UAL.BLL.Data;
using UAL.BLL.Models;

namespace UnitedAccessoriesLimited.Controllers
{
    public class FollowUpController : Controller
    {
        //
        // GET: /FollowUp/

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Indent I)
        {
            string[] lists = Request.Form.GetValues("follow[]");
            Session["list"] = lists;
            if (Request.Form["submitbutton1"] != null)
            {
                return RedirectToAction("List");
            }
            else if (Request.Form["submitButton2"] != null)
            {
                return RedirectToAction("Payment");
            }
            return View();
            
        }
        public ActionResult Payment()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Payment(Payment p)
        {
            if (Session["PaymentSub"]!=null && Session["PaymentSub"].ToString() == "Yes")
            {
                return RedirectToAction("ProformaInvoice");
            }
            Session["BankName"] = p.PaymentMethod;
            Session["BankAddress"] = p.BankAddress;
            Session["BankSwift"] = p.Swift;
            Session["BankAccountNo"] = p.AccountNo;

            Session["PaymentSub"] = "Yes";
            PaymentRepository pr = new PaymentRepository();
            pr.SubmitPayment(p);
            return View();
        }
        public ActionResult ProformaInvoice()
        {
            long[] myInts = Array.ConvertAll((String[])Session["list"], s => long.Parse(s));
            PaymentRepository pr = new PaymentRepository();
            int invoiceNumber = pr.getInvoiceNumber();
            List<Indent> li= pr.getProformaInvoice(myInts);
            Session["invoiceNumber"] = invoiceNumber;
            
            return View(li);
        }
        public ActionResult List(String[] list)
        {
            long[] myInts = Array.ConvertAll((String[])Session["list"], s => long.Parse(s));
            OrderRepository or = new OrderRepository();
            List<Indent> li = or.getFollowUpList(myInts);
            return View(li);
        }
        public ActionResult CreateIndent()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateIndent(Indent I)
        {
            OrderRepository or = new OrderRepository();
            string[] wo = Request.Form.GetValues("workOrder[]");
            string[] refN = Request.Form.GetValues("refN[]");
            var woAndRefN = wo.Zip(refN, (w,r) => new { WorkOrder = w, Reference = r });
            long sil = or.getSIL();
            foreach (var x in woAndRefN)
            {
                
                or.createIndent(x.WorkOrder,x.Reference,sil);
            }
            return View();
        }
    }
}

UnitedAccessoriesLimited/Views/FollowUp/CreateIndent.cshtml
@model UAL.BLL.Models.Indent

@{
    ViewBag.Title = "CreateIndent";
}
<script>
    $(document).ready(function () {
        var max_fields = 10; //maximum input boxes allowed
        var wrapper = $(".input_fields_wrap"); //Fields wrapper
        var add_button = $(".add_field_button"); //Add button ID

        var x = 1; //initlal text box count
        $(add_button).click(function (e) { //on add input button click
            e.preventDefault();
            if (x < max_fields) { //max input box allowed
                x++; //text box increment
                $(wrapper).append('<div><br><input type="text" name="workOrder[]"/> <input type="text" name="refN[]"/> <a href="#" class="remove_field">Remove</a></div>'); //add input box
            }
        });

        $(wrapper).on("click", ".remove_field", function (e) { //user click on remove text
            e.preventDefault(); $(this).parent('div').remove(); x--;
        })
    });
</script>
<div id="main1" style="margin-left:195px">
    <h2>CreateIndent</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Indent</legend>
            <div class="input_fields_wrap">
                <button class="add_field_button">Add More Fields</button>
                <div>
                    <span style="font-weight:bold">Work Order Reference</span>
                    <span style="font-weight: bold;margin-left:150px">Buyer Reference #</span>
                </div>
                <div><input type="text" name="workOrder[]"> <input type="text" name="refN[]"></div>
                
            </div>
            @*<div class="editor-label">
                    @Html.LabelFor(model => model.IndentNo)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.IndentNo)
                    @Html.ValidationMessageFor(model => model.IndentNo)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.WorkOrder)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.WorkOrder)
                    @Html.ValidationMessageFor(model => model.WorkOrder)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.ReferenceNo)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.ReferenceNo)
                    @Html.ValidationMessageFor(model => model.ReferenceNo)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Status)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status)
                </div>*@

            <p>
                <br />
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
</div>

UnitedAccessoriesLimited/Views/FollowUp/Index.cshtml
@model UAL.BLL.Models.Indent
@{
    ViewBag.Title = "Index";
}

<script>
    $(document).ready(function () {
        var max_fields = 10; //maximum input boxes allowed
        var wrapper = $(".input_fields_wrap"); //Fields wrapper
        var add_button = $(".add_field_button"); //Add button ID

        var x = 1; //initlal text box count
        $(add_button).click(function (e) { //on add input button click
            e.preventDefault();
            if (x < max_fields) { //max input box allowed
                x++; //text box increment
                $(wrapper).append('<div><br>SIL-<input type="number" name="follow[]" min="0" required/><a href="#" class="remove_field">Remove</a></div>'); //add input box
            }
        });

        $(wrapper).on("click", ".remove_field", function (e) { //user click on remove text
            e.preventDefault(); $(this).parent('div').remove(); x--;
        })
    });
</script>
<div id="main1" style="margin-left:195px">
    @Html.ActionLink("Create Indent", "CreateIndent", new { }, new { @class = "linkX" })
    @using (Html.BeginForm("Index","FollowUp",FormMethod.Post, new { target = "_blank" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Get Follow-Up</legend>
            <div class="input_fields_wrap">
                <button class="add_field_button">Add More Fields</button>
                <div>
                    <span style="font-weight:bold">Indent No (Type only numbers)</span>
                </div>
                <div>SIL-<input type="number" name="follow[]" min="0" required></div>

            </div>
            <p>
                <br />
                <input type="submit" name="submitbutton1" value="Get Follow Up" />
                <input type="submit" name="submitbutton2" value="Get Proforma Invoice" />
            </p>
        </fieldset>
    }
</div>

UnitedAccessoriesLimited/Views/FollowUp/List.cshtml
@model IEnumerable<UAL.BLL.Models.Indent>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FOLLOW-UP</title>
    <style>
        body {
            font-family: Calibri;
            margin-left: 3%;
            margin-right: 3%;
        }

        table {
            width: 100%;
        }

        #list td {
            text-align: center;
            font-weight: bold;
        }

        #list tr th {
            border: 1px solid black;
            text-align: center;
        }

        #list tr td {
            border: 1px solid black;
            text-align: center;
        }


        #head{
            margin-bottom: 10px;
        }
         #head tr td {
            border: 2px solid black;
            text-align: right;
        }
         #foot tr td{
             border: 1px solid black;
         }
    </style>
    <style type="text/css" media="print">
        @@page {
            size: auto; /* auto is the initial value */
            margin: 0; /* this affects the margin in the printer settings */
        }
    </style>
</head>
<body>
    <h2 style="text-align:center;text-decoration:underline">FOLLOW-UP</h2>
    <span style="float:right">@DateTime.Now.ToString("dd MMMM, yyyy")</span>
    @{int i = 1;
      double total = 0;}
    <table id="head">
        <tr>
            <td width="65px" style="border:0px"></td>
            <td>
                @{
                var result = Model.Select(m=>m.Order.CustomerName).ToList().FirstOrDefault();
                var ls = Model.Select(m => m.IndentNo).Distinct();
            }
                @Html.DisplayFor(modelItem => result)
                // Indent No. SIL- 
            @foreach (var item in ls)
            {
                if (item != ls.Last()) { 
                <span>@item,&nbsp;</span>
            }
                else
                {
                    <span> & @item</span>
                }
              
            }
                <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -2016</span>
        </td>
    </tr>

</table>
<table id="list" cellpadding="0" cellspacing="0">
    <tr>
        <th>
            IND. #
        </th>
        <th>SL #</th>
        <th>Item Description</th>
        <th>
            Buyer's Ref.
        </th>
        <th>
            COM.
        </th>
        <th>
            Quantity In Pcs.
        </th>
        <th>
            UAL W/O # & Date.
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>

    </tr>
    @{var x = Model.ToList().FirstOrDefault();}
    @foreach (var item in Model)
    {
        total = total + item.Order.OrderQty * Convert.ToDouble(item.ArtWorkUpload.Price);
        int rowspan = 1;
        if (item.IndentNo != x.IndentNo || i == 1)
        {
            <tr style="height:20px; border:0px">
                <td style="border:0px; border-left:1px solid black"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
            </tr>
        }
        x = item;
        <tr>

            <td rowspan="@rowspan">
                SIL-@Html.DisplayFor(modelItem => item.IndentNo)
            </td>
            <td>
                @i
                @{i++;}
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArtWorkUpload.itemDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReferenceNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArtWorkUpload.combo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Order.OrderQty)
            </td>
            <td style="text-align:right;padding-right:10px">
                @Html.DisplayFor(modelItem => item.WorkOrder)
                <span style="font-size:8px"><br /> DT-@item.Order.Date.ToString("dd.MM.yy")</span>
            </td>
            @{if (DateTime.Now.Date > @item.Order.DeliveryDate)
            {
                <td>
                    Ready to dispatch
                </td>
            }
            else if (DateTime.Now.Date < @item.Order.DeliveryDate)
            {
                <td style="background-color:#bfbfbf">
                    Will be ready on @item.Order.DeliveryDate.ToString("dd.MM.yy")
                </td>
            }
            else
            {
                <td>
                    Already DISPATCHED
                </td>
            }
            }


        </tr>
    }

</table>
    <table id="foot" style="text-align: right; width: 60%; float: left; margin-top: 30px" cellspacing="0">
        <tr>
            <td style="padding-right:5px">PI issue & Sent</td>
            <td width="40%"></td>
        </tr>
        <tr>
            <td style="padding-right:5px">Signed PI Rcvd.</td>
            <td></td>
        </tr>
        <tr>
            <td style="padding-right:5px">TT Rcvd</td>
            <td></td>
        </tr>
        <tr>
            <td style="padding-right:5px">EXP</td>
            <td></td>
        </tr>
        <tr>
            <td style="padding-right:5px">SHPT. MODE</td>
            <td></td>
        </tr>
        <tr>
            <td style="padding-right:5px">Forwarder</td>
            <td></td>
        </tr>
        <tr>
            <td style="padding-right:5px">DELIVERED</td>
            <td></td>
        </tr>
    </table>
    <table style="float: right; border: 2px solid black; margin-top: 30px;width:30%">
        <tr>
            <td style="text-align:left; border-right:2px solid black">
                <b>TOTAL =</b>
            </td>
            <td style="text-align:right">
                $@total
            </td>
        </tr>
    </table>
</body>
</html>

UnitedAccessoriesLimited/Views/FollowUp/Payment.cshtml
@model UAL.BLL.Models.Payment

@{
    ViewBag.Title = "Payment";
}
<div id="main1" style="margin-left:195px">
    <h2>Payment</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Payment</legend>

            <div class="editor-label">
                Bank Name
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PaymentMethod)
                @Html.ValidationMessageFor(model => model.PaymentMethod)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.BankAddress)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.BankAddress)
                @Html.ValidationMessageFor(model => model.BankAddress)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Swift)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Swift)
                @Html.ValidationMessageFor(model => model.Swift)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.AccountNo)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.AccountNo)
                @Html.ValidationMessageFor(model => model.AccountNo)
            </div>

            <p>
                <input type="submit" value="Submit" />
            </p>
            @if (Session["PaymentSub"] != null && Session["PaymentSub"].ToString() == "Yes")
            {
                using (Html.BeginForm("ProformaInvoice", "FollowUp", FormMethod.Post, new { target = "_blank" }))
                {

                    <p>
                        <br />
                        <input type="submit" name="submitbutton1" value="Get ProformaInvoice" />

                    </p>

                }
            }
        </fieldset>
    }
</div>

UnitedAccessoriesLimited/Views/FollowUp/ProformaInvoice.cshtml
@model IEnumerable<UAL.BLL.Models.Indent>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ProformaInvoice</title>
    <style>
        body {
            font-family: Calibri;
            margin: 5%;
        }

        #tablex {
            width: 100%;
        }

            #tablex th {
                border: 1px solid black;
            }

            #tablex td {
                border: 1px solid black;
                text-align: center;
            }

        #tf {
            width: 100%;
        }
    </style>
    <style type="text/css" media="print">
        @@page {
            size: auto; /* auto is the initial value */
            margin: 0; /* this affects the margin in the printer settings */
        }
    </style>
</head>
<body>
    <div>
        <h3 style="text-decoration:underline; text-align:center">PROFORMA INVOICE</h3>
        <div>
            <div style="float:right">
                <b>UAL</b>/EXP/@DateTime.Now.Year/<b>@Convert.ToInt32(Session["invoiceNumber"])</b>
                <br />
                @DateTime.Now.ToString("dd MMMM, yyyy")
            </div>
            <br />
        </div>
        <br />
        <br />
        <table style="text-align:center">
            <tr style="text-decoration:underline">
                <th>BUYER:</th>
                <th>SELLER/BENEFICIARY:</th>
                <th>BENEFICIARY'S BANK ADDRESS:</th>
            </tr>
            <tr>
                <td>Buyer</td>
                <td>Union Accessories Limited</td>
                <td>@Session["BankName"]</td>
            </tr>
            <tr>
                <td>NZ Center, Plot # 5, Road # 12, Sector # 6, Uttara, Dhaka 1230, Bangladesh
                    Tel: 8802-8917638, 8954473 Fax: 8802-8923994</td>
                <td>
                    NZ Center, Plot # 5, Road # 12, Sector # 6, Uttara, Dhaka 1230, Bangladesh
                    Tel: 8802-8917638, 8954473 Fax: 8802-8923994
                </td>
                <td>@Session["BankAddress"] <br /> @Session["BankSwift"] <br /> @Session["BankAccountNo"]</td>
            </tr>
        </table>
        <div style="text-decoration:underline">
            <b>REF: </b>Indent No. <b>SIL-</b>

            @{
                var ls = Model.Select(m => m.IndentNo).Distinct();
            }
            @foreach (var item in ls)
            {
                if (item == ls.First())
                {
                    <span>@item</span>
                }
                else if (item != ls.Last())
                {
                    <span>, @item</span>
                }
                else
                {
                    <span> & @item</span>
                }

            } --2016
        </div>
        <br />
        <table cellspacing="0" id="tablex">
            <tr id="head">
                <th>SL #</th>
                <th>Item Description</th>
                <th>PO #</th>
                <th>Buyer's Ref.</th>
                <th>COM.</th>
                <th>Quantity In Pcs.</th>
                <th>Quantity In Dzn.</th>
                <th>Price Per Dzn. (US$)</th>
                <th>Amount (US $)</th>
            </tr>
            @{decimal tot = 0;
            decimal am = 0;}
            @{int i = 1;}
            @{var x1 = Model.ToList().FirstOrDefault();}
            @foreach (var item in Model)
            {
                if (item.IndentNo != x1.IndentNo || i == 1)
                {
                    <tr style="height:10px; border:0px">
                        <td style="border:0px; border-left:1px solid black"> </td>
                        <td style="border:0px"> </td>
                        <td style="border:0px"> </td>
                        <td style="border:0px"> </td>
                        <td style="border:0px"> </td>
                        <td style="border:0px"> </td>
                        <td style="border:0px"> </td>
                        <td style="border:0px"> </td>
                        <td style="border: 0px; border-right: 1px solid black"> </td>
                    </tr>
                }
                x1 = item;
                <tr>
                    <td>
                        @i
                        @{i++;}
                    </td>
                    <td>@item.ArtWorkUpload.itemDescription</td>
                    <td rowspan="1">@item.Order.Breakdowns.Where(m=>m.OrderNo == item.Order.OrderRef).Select(m=>m.PONumber).ToList().FirstOrDefault()</td>
                    <td>@item.ReferenceNo</td>
                    <td>@item.ArtWorkUpload.combo</td>
                    <td>@item.Order.OrderQty</td>
                    <td>
                        @{decimal x = Convert.ToDecimal(item.Order.OrderQty) / 12;
                        string y = x.ToString("F");}
                        @y
                    </td>
                    <td>@item.ArtWorkUpload.Price</td>
                    <td style="text-align:right">
                        @{am = Convert.ToDecimal(item.ArtWorkUpload.Price) * Convert.ToDecimal(item.Order.OrderQty);
                        tot += am;
                        string amn = am.ToString("F");}
                        @amn
                    </td>
                </tr>

            }
            <tr style="height:10px; border:0px">
                <td style="border:0px; border-left:1px solid black"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
                <td style="border:0px"> </td>
            </tr>
            <tr>
                <td colspan="8" style="text-align:left"><b>Bank Charges: </b></td>
                <td style="text-align:right">
                    @{decimal bc = Convert.ToInt32(tot / 100);}
                    @{string bankCharges = "$" + bc.ToString("#.");}
                    @bankCharges<span>.00</span>
                </td>
            </tr>
            <tr>
                <td colspan="8" style="text-align:right; border: 0; font-weight:bold">
                    TOTAL =
                </td>
                <td style="text-align:right">
                    <b>
                        @{decimal total = tot + bc;}
                        $@total
                    </b>
                </td>
            </tr>
        </table>
        <b> Amount in words: </b><span style="text-decoration:underline" id="amInW"></span>
        <script>
            var th = ['', 'thousand', 'million', 'billion', 'trillion'];
            // uncomment this line for English Number System
            // var th = ['','thousand','million', 'milliard','billion'];

            var dg = ['zero', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
            var tn = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
            var tw = ['Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
            //function toWords(s) {
            var s = Number(@total);
            //alert(s);
            s = s.toString(); s = s.replace(/[\, ]/g, '');
            // if (s != parseFloat(s)) return 'not a number';
            var x = s.indexOf('.'); if (x == -1) x = s.length;
            //  if (x > 15) return 'too big';
            var n = s.split('');
            var str = '';
            var sk = 0;
            for (var i = 0; i < x; i++) {
                if ((x - i) % 3 == 2) {
                    if (n[i] == '1') {
                        str += tn[Number(n[i + 1])] + ' '; i++; sk = 1;
                    }
                    else if (n[i] != 0) { str += tw[n[i] - 2] + ' '; sk = 1; }
                }
                else if (n[i] != 0) {
                    str += dg[n[i]] + ' ';
                    if ((x - i) % 3 == 0) str += 'hundred '; sk = 1;
                }
                if ((x - i) % 3 == 1) { if (sk) str += th[(x - i - 1) / 3] + ' '; sk = 0; }
            }
            if (x != s.length) {
                var y = s.length; str = '<b>' + str + '</b> ' + '& cents ';
                for (var i = x + 1; i < y; i++) {
                    if (i == x + 1) {
                        str = str + '<b>' + tw[n[i] - 2] + '</b>' + ' ';
                    }
                    else {
                        if (n[i] != 0)
                            str = str + '<b>' + dg[n[i]] + '</b>';

                    }

                }

            };

            //alert(str.replace(/\s+/g, ' '))
            document.getElementById("amInW").innerHTML = "United States Dollar " + str.replace(/\s+/g, ' ') + " only.";

            // return str.replace(/\s+/g, ' ');

        </script>
        <h4 style="text-decoration:underline; ">Terms & Conditions</h4>

        <ol type="a">
            <li>
                Payment to be made by Telegraphic Transfer favouring Union Accessories Limited <b>A/C# @Session["BankAccountNo"]</b>
                with <b>@Session["BankName"]</b>, @Session["BankAddress"]. @Session["BankSwift"].
            </li>
            <li>
                The Shipment will be made after receipt of fund by Telegraphic Transfer in favour of the beneficiary.
            </li>
            <li>
                Please mention our <b>P/I</b> number <b>
                    UAL/EXP/@DateTime.Now.Year/
                    @Convert.ToInt32(Session["invoiceNumber"])
                </b>
                in place of purpose of remittance.
            </li>
            <li>
                Above mentioned prices are <b>EX-FACTORY</b>.
            </li>
            <li>
                All charges outside Bangladesh will be on buyer's account.
            </li>
        </ol>
        <h4 style="text-decoration:underline; margin-bottom:50px;">Accepted:</h4>
        <table id="tf">
            <tr style="font-weight:bold">
                <td style="width:20%;text-align:center; border-top: 1px solid black">Authorised Signature<br />BUYER Name</td>
                <td style="width:60%"></td>
                <td style="width:20%; text-align: center; border-top: 1px solid black">Authorised Signature<br />UNION ACCESSORIES LIMITED</td>
            </tr>
        </table>
        <div style="text-align:center">
            Office: NZ Center, Plot # 5, Road # 12, Sector # 6, Uttara, Dhaka 1230, Bangladesh
            <br /> Tel: 8802-8917638, 8954473, 8917510, 8933248 Fax: 8802-8923994 E-mail: shahed@uniobd.net
        </div>
    </div>
</body>
</html>